### ISSUE TITLE
How to handle service worker unregister?

### ISSUE THREAD

**Issue by gauntface** [w3c/push-api#121]
If a user deletes cookies and the service worker is unregistered - how should a developer deal with this?

Waiting for the push service to respond with a bad error message feels kind of bad / suboptimal - could we add an event to handle this scenario allowing developers to have some opportunity to react?

**Comment by johnmellor** [comment]
> If a user deletes cookies and the service worker is unregistered - how should a developer deal with this?

The next time the user visits the website, it'll be like they're visiting it for the first time, so the developer shouldn't have to do anything special to handle that.

The developer will end up with a stale subscriptionId on their server, which shouldn't be disastrous (this can also occur if the user factory-resets their device, or breaks the device by dropping it, etc). And as you mentioned, push servers may provide ways of cleaning these up, for example GCM replies with [error responses](https://developer.android.com/google/gcm/server-ref.html#interpret-downstream) when it knows that a subscriptionId is stale (though that won't help for factory-reset or broken device, as GCM won't know it's stale), and also offers [delivery receipts](https://developer.android.com/google/gcm/ccs.html#receipts).

> could we add an event to handle this scenario allowing developers to have some opportunity to react?

The event would have to fire _before_ cookies are cleared (since, at least in Chrome, clearing cookies also unregisters the Service Worker etc, so there would be nowhere to deliver the event). Might still be useful I guess, but it'd only work if the device happens to be online (since cookies -- and hence all other storage -- are being cleared, the site wouldn't be able to use a one-shot [background sync](https://github.com/slightlyoff/BackgroundSync/blob/master/explainer.md) or similar to notify its server when next online).

**Comment by gauntface** [comment]
I suppose the question I'm trying to ask is, can we do better than just wait for GCM to tell us after we've tried to send a push?

I suppose native apps don't really have any way around this either.

**Comment by mvano** [comment]
I think one can also ask the question "do you want to make the clearing of cookies and cache detectable in javascript?"

**Comment by gauntface** [comment]
@mvano you are right, none of this makes sense and is probably worrying about a problem that doesn't need worrying about.
