### ISSUE TITLE
Allow UAs to unsubscribe offline "successfully"

### ISSUE THREAD

**Issue by johnmellor** [w3c/push-api#122]
The [unsubscribe algorithm](https://w3c.github.io/push-api/#widl-PushSubscription-unsubscribe-Promise-boolean) currently says:

> If it was not possible to access the push service, reject promise with a "NetworkError" exception and terminate these steps.

But it would be a nicer developer experience if unsubscribe were to immediately clear local state\* and resolve the promise successfully, then retry automatically to tell the push server about the unsubscription with exponential backoff (which may eventually give up).

This is what UAs must implement anyway if the website unregisters their Service Worker, since that will succeed irrespective of whether the device is offline.

Let's either require this in the spec, or change the language to allow a UA to do this, whilst permitting other UAs to still return NetworkErrors if they prefer that.

*: by clear local state, I mean make sure that `getSubscription()` resolves as `null`, and push messages are no longer delivered to the Service Worker. Until the unregistration is successfully transmitted to the push server, the push server will still consider it valid (which the developer may be able to observe).

**Comment by johnmellor** [comment]
@martinthomson @gauntface

**Comment by martinthomson** [comment]
I don't see why you couldn't mark subscriptions as dead and kill them when you next talk to the server.  A simple approach would be to avoid (i.e., defer) all interactions with subscriptions unless you are "connected".  No need for retrying and back-off and all that nasty stuff.

I think that you probably need to allow that, since you are going to want to clean up subscriptions in some cases anyway.  For instance, if a user clears cookies for that origin.

**Comment by gauntface** [comment]
I think calling unsubscribe while you are offline, should result in the push messages to stop. There will be two main places for concerns:

1.) The browser
   a.) unsubscribing with the push service - this problem doesn't need to be passed on to the developer.
   b.) Ensuring push messages don't get passed to the service worker

2.) The developer 
  a.) needs to unsubscribe on their server - the developer can handle with what ever method they wish too.

 I think your proposal makes sense. I would rather we pushed to get this behavior as the required behavior rather than optional, otherwise we'll push developers to alter their implementation on a range of browsers.

**Comment by martinthomson** [comment]
Step 5 of the unsubscribe() operation is just wrong.  We should allow the UA to retry on network failures.  And we should insist that no more messages are delivered.
