### ISSUE TITLE
Rename hasPermission

### ISSUE THREAD

**Issue by mvano** [w3c/push-api#136]
The promise for `hasPermission` is resolved with an enum, not a boolean. This seems slightly inconsistent,  `hasPermission` suggests a boolean.

I suggest we rename it to `getPermission`.

@annevk suggested renaming it to `permission` as that's what the Notifications API facility is called. But in the Notifications API it is a property, not a method, and method names should really be verbs. Anne, what do you think?

CC @beverloo

**Comment by annevk** [comment]
Naming it `permission()` would be fine with me (so similar, but a method). `getPermission()` might imply that it involves the user. Others from Google suggested `getPermissionState()` over in the BackgroundSync repo, but to me that seems overly verbose.

**Comment by phistuck** [comment]
Reading all of those example tells me that a `PrivilegedAPI` (or similar) interface is needed and any API that needs a permission should inherit from it. This ensures consistency.
(And in general, a "privileged API" concept that ensured automatic inclusion in the Permissions API and in the "not available to insecure pages" concept)

**Comment by mvano** [comment]
@phistuck : in future, once the Permissions API has shipped widely, methods like this are unlikely to be added to individual APIs anymore. Until that time, I think we can make do on a case by case basis, just to support the use cases enabled by this method. Now that the Permissions API spec exists, I don't see much value in standardizing an additional interface anymore.

**Comment by mvano** [comment]
The feedback in general on this issue, and in in-person discussions, has lacked a clear consensus on which name to use, other than people agree that `hasPermission` is a poor name. I'll go with the middle road between compactness and verbosity and rename it to `getPermission`.

**Comment by beverloo** [comment]
I would like to raise some caution in regards to ensuring consistency with Background Sync. Have we reached out to them to make sure they are OK with getPermission()?

**Comment by mvano** [comment]
I've poked the identical BackgroundSync issue to try and align these method names: https://github.com/slightlyoff/BackgroundSync/issues/39

**Comment by annevk** [comment]
You don't think that `getPermission()` is awfully similar to `requestPermission()`?

**Comment by mvano** [comment]
@annevk I don't, but then again I like Java.

**Comment by mvano** [comment]
As an example of how this is pretty natural in Java, see HttpServletRequest. A whole host of methods starting with `get` which does look pretty verbose, but... there are methods like `getRequestURL()`. That would look pretty odd as `requestURL()`. That verbosity provides clarity and consistency e.g. when there are also setters, at a cost. I'm ok with making our own APIs more compact, as long as we don't lose too much clarity while doing so.

**Comment by martinthomson** [comment]
If you were going for Java's naming convention, it would be `isPermitted()`, wouldn't it?

**Comment by beverloo** [comment]
API design decisions made in the Java libraries seem entirely orthogonal to me? While WebIDL does allow for implementations in other languages, the foremost candidate will be JavaScript.

> You don't think that getPermission() is awfully similar to requestPermission()?

Reading the method name, one would "get permission" from the "push manager". I agree that this is confusing - linguistically the act of getting permission is ambiguous, and does not clarify whether it will just return the current status or actually request permission from the user.

> Naming it permission() would be fine with me (so similar, but a method).

That might cause confusion with `Notification.permission`, which is what some early adopters of the Push API in Chrome (unfortunately) are using to check the permission status, as it returns a boolean. We won't be able to change that to return a Promise due to maintaining backwards compatibility.

> Others from Google suggested getPermissionState() over in the BackgroundSync repo

getPermissionState() is clear on both counts, but also very verbose. A typical use of the API could end up looking as follows:

`serviceWorkerRegistration.pushManager.getPermissionState().then(...)`

(Making me remember the days where pushManager was called pushRegistrationManager.)

I don't have a strong preference for either of these method names. To throw in another alternative that could be considered: `checkPermission`.

**Comment by mvano** [comment]
All of this Java related discussion was just to indicate that the `get` prefix, to many people, has a clear meaning, and it helps structure large code bases. It indicates a getter without side effects, and is often paired with methods starting with `set`. It would be rather unlikely for those people to confuse that with `request`. Anyway, I realize that this is a Java pattern, and it doesn't work for everyone. In the parallel BackgoundSync issue we've already moved past this, and we can probably do so here also.

**Comment by miguelgarciaarribas** [comment]
I think the background sync folks settled on permissionState so let's just go with that.

**Comment by miguelgarciaarribas** [comment]
https://github.com/w3c/push-api/pull/139 for your consideration

**Comment by beverloo** [comment]
@annevk Just to confirm - are you OK with the permissionState() name?

**Comment by annevk** [comment]
I can live with it.
