### ISSUE TITLE
Change references to webapp => service worker

### ISSUE THREAD

**Issue by efullea** [w3c/push-api#15]
Change references to webapp => service worker where it might be unclear that only Service Workers should use interfaces & get events etc. Other than register (because of the need for permissions UI), all interfaces and events to SW only

**Comment by mvano** [comment]
Even register should probably exposed inside the Service Worker. If a PushError is fired indicating that the registration was lost, re-registration could take place inside the SW assuming the permission has not been revoked. If the permission was also revoked, and no UI can be displayed due to running in the background, the re-registration call can fail indicating permission is not granted yet. Might even say it is due to running in the background. What do you think?

**Comment by nikhilm** [comment]
Is the pushRegistration still unique per webapp or per serviceworker (scope)?

**Comment by mvano** [comment]
@nikhilm I think per `ServiceWorkerRegistration` makes most sense considering that's how the Push API will be exposed, see issue #2.

**Comment by mvano** [comment]
Adding @johnmellor for additional details.

**Comment by nikhilm** [comment]
works for gecko.
