### ISSUE TITLE
Allow UA to not implement all PushSubscriptionOptions

### ISSUE THREAD

**Issue by martinthomson** [w3c/push-api#200]
These need to be truly optional.  If a UA doesn't implement X, then it shouldn't be obliged to remember values that were set by applications.

**Comment by beverloo** [comment]
How would this impact the code of someone using `PushSubscription.options`? In case of `userVisibleOnly`, since `undefined` is falsy, I suspect we're good. This might be more of a concern for VAPID's `applicationServerKey`.

The (supposedly) common case of using this to resubscribe would not be impacted:

``` javascript
self.addEventListener('pushsubscriptionchange', event => {
  event.waitUntil(
      pushManager.subscribe(event.oldSubscription.options).then(...));
});
```

What about the following addition after the first paragraph of section 8.1?

> These options are optional, and user agents MAY choose to support only a subset of them. User agents SHOULD NOT expose options it does not support.

Somewhat orthogonal, but I would very much like to see this for notifications too: exposing properties based on availability of the feature on the user's host platform.

**Comment by martinthomson** [comment]
Presumably, if the UA doesn't support member X, then it can omit X from `PushSubscription.options`.  Given that the most obvious use for that is to pass it back to the UA, then not having X will be functionally equivalent (since the UA would ignore X even if it is present).

Even if it did retain X, there would be no harm other than muddying the situation: applications wouldn't be able to work out what was supported vs. not.

> I would very much like to see this for notifications too: exposing properties based on availability of the feature on the user's host platform.

Yes, feature detection is a basic right :)
