### ISSUE TITLE
User preference for timing

### ISSUE THREAD

**Issue by 7mary4** [w3c/push-api#257]
The document states clearly the user must authorize the push:

> User agents MUST NOT provide Push API access to webapps without the express permission of the user. User agents MUST acquire consent for permission through a user interface for each call to the subscribe() method, unless a previous permission grant has been persisted, or a prearranged trust relationship applies. Permissions that are preserved beyond the current browsing session MUST be revocable.

There’s also a section for how to deal with expired pushes and a section for push subscription options.

Does this allow a user to set a period of time between pushes?

For instance, a person may take longer to read/complete a sequence due to a disability. If the screen changes too quicklly, due to a push, they could lose track of what they are doing. For these users, they may prefer to change their settings.

**Comment by beverloo** [comment]
Hi Ted, thank you for your report! The Push API is a communication protocol and defines means through which a message could _reach_ the user. The developer then has to use other features to _display_ the content to the user, if at all necessary. To give some example options:

- Displaying a notification. This is the common case, where the [Notifications API](https://notifications.spec.whatwg.org) is used to display the notification. This often means that display, and options thereof, are delegated to the underlying operating system.

- Updating an opened page. Notably, displaying the received message in an already opened chat window, or comment stream. This, as well as the pursuing layout changes, is entirely the developer's doing.

- Update the cache. In this case nothing has to be displayed to the user at all.

Specifically to your question, I feel that it's a shared responsibility between the user agent (who choses a notification center) and the operating system (who usually provides one) to ensure displayed notifications are sufficiently accessible. However, since the act of _displaying_ content is out of scope of this specification, I'm not sure whether adding a note would be sufficiently beneficial.

**Comment by martinthomson** [comment]
@7mary4, please see the discussion on #259, where the same issue was raised.  There, the suggestion was to take this up as an accessibility note on the Notifications API.
