### ISSUE TITLE
How do I authenticate a user

### ISSUE THREAD

**Issue by ghost** [w3c/push-api#314]
In my database, all  users don't have login (they are in "groups" which have their own "secrets") and I was wondering if a push subscription has a unique secret that could be used for that. Is "auth" or "p256dh" unique & safe to use as a secret?/

**Comment by collimarco** [comment]
You can simply **associate each push subscription that you store in your database to a user (ID)**. We use that for Pushpad and it works perfectly.

**The "unique secret" is simply the endpoint**. That is granted by the standard (consider that in the past the endpoint was the only thing required in order to send a push message).

**Comment by marcoscaceres** [comment]
Closing as answered.
