### ISSUE TITLE
Specification status report for TPAC 2019

### ISSUE THREAD

**Issue by LJWatson** [w3c/push-api#316]
Please can you respond to this comment with a brief specifications status report for the WebApps meeting at TPAC. The report should address the following:
* What progress has your spec made in the last 12 months?
* Is anything blocking your spec from moving to CR?
* If yes, what is your plan to unblock it and do you need any help?
* What do you want to achieve for your spec in the next two days (of breakout sessions)?

We're tracking these status reports in [WebApps issue #19](https://github.com/w3c/webappswg/issues/19)

Thanks.

**Comment by marcoscaceres** [comment]
@beverloo, any chance you could help us with the questions above for TPAC? Looking forward to seeing you there!

**Comment by beverloo** [comment]
Apologies for the late response, from @martinthomson and myself:

> What progress has your spec made in the last 12 months?

No real changes over the last 12 months.  The spec is in most ways stable.  Editorial changes have been made, and alignment with updates in dependencies has been improved.

> Is anything blocking your spec from moving to CR?

A few things: resourcing, ambivalence, and churn. 

The editors are quite busy with other more important tasks and so were unable to dedicate additional time.  Getting to the point where we have good test coverage in WPT takes considerable investment that we can't currently justify, largely due to missing infrastructure.  We believe that the spec is in good shape for the most part otherwise.

The ambivalence is over the perceived value of a candidate recommendation.  Any such label is unlikely to be more useful than a spec that we can continue to update.  We can prepare a document that could progress among the REC track as a snapshot by end of year if the Chairs prefer.

Finally, there has been a bunch of churn in areas that the spec depends on.  WebIDL continues to make incompatible changes (e.g., #312) as does the service worker spec (e.g., #315).  We've also seen a lot of changes out of Respec, though Marcos was kind enough to spend some time cleaning things up, which was very much appreciated.  What limited resources we have are dedicated to managing this churn rather than in advancing the specification.

> If yes, what is your plan to unblock it and do you need any help?

We don't see an urgent need to unblock things for the above reasons.

> What do you want to achieve for your spec in the next two days (of breakout sessions)?

We have no current plans for the spec.  Peter is attending TPAC, but Martin is not.

**Comment by martinthomson** [comment]
Closing this one now that it has served its purpose.
