### ISSUE TITLE
Permission checks in the push API

### ISSUE THREAD

**Issue by miguelgarciaarribas** [w3c/push-api#75]
Currently Chrome only grants permissions for a combination of iframe + embedder.

Therefore if you ask say for geolocation from b.com as an iframe of a.com. The permission will only be granted for that combination and not when b.com is in an iframe of c.com or if you go directly to b.com as a top level domain.

In the context of push this will not work since a SW is only tight to its embedder.

I therefore propose that we only allow push permissions for top level domains. iframes will not be able to have the push permission granted.

Perhaps this is just a chrome specific thing and too much detail to have it added to the spec but at least this is probably how Chrome is going to have to ship this API.

**Comment by martinthomson** [comment]
This is reasonable.  We should permit the iframe if it is on the same origin as the embedder.

**Comment by miguelgarciaarribas** [comment]
Good to know, do you think it'd be possible to add it to the spec in some form? perhaps a non normative reference?

**Comment by mounirlamouri** [comment]
In other words, the registration request would fail if the iframe isn't already allowed to use Push, right? If I load foo.com from an iframe but foo.com was previously granted push permissions, Chrome would allow push to be used by foo.com?

I'm not sure if that needs to be part of the specification in the sense that when foo.com will try to register, it will get a rejection because of permission not granted and if foo.com query its permission status, it will see 'deny' when inside an iframe but 'granted' when loaded as a top level browsing window. The fact that foo.com might not be able to register because the permission isn't granted is definitely something that it should take into account already, right?

WDYT?

**Comment by martinthomson** [comment]
@mounirlamouri, I'm not sure that I get your concern?

I think that a consent dialog needs to be associated with a top-level browsing context, but once authorization is granted, I see no reason to prevent access from frames.

As a general matter, we shouldn't be making UX assertions, but note that:
- push requires access to computing resources outside of the times when a user might expect those resources to be available to a site (e.g., when no tabs are open to the site)
- therefore, access to push in this context requires some form of (user) authorization to permit beyond just navigating to a page
- if authorization is granted using a user consent interaction, these are generally implicitly attributed to a top-level browsing context; therefore, if the origin requesting authorization is not the same as that in the top-level browsing context, that might be confusing to users

I'm fairly sure that our respecting UX people know what to do with that information.

As a matter for the API, a registration will be rejected if it cannot acquire authorization.  Whether the registration attempt triggers the creation of a consent dialog will depend on several things.  I'm not sure that there is any value in exposing the specific reasons that consent was not granted.

What we could do is note that framed contexts that don't match the top-level context might only be able to rely on a persisted authorization that was previously established, since there might not be any opportunity to acquire that authorization.

**Comment by mvano** [comment]
There seems to be a general consensus that the details of the permissions UX are user agent specific. The spec says to reject the promise with a PermissionDeniedError if the user does not grant permission, the rest is up to the UA. I'm closing this issue, but I'm happy to pursue clarifications if it later turns out there is confusion that the spec could prevent.

Chrome currently requires the requesting origin and the embedding (top level) origin to match for the permission request (triggered by subscribe). Here's the PushMessagingPermissionContext class:
https://code.google.com/p/chromium/codesearch#chromium/src/chrome/browser/services/gcm/push_messaging_permission_context.cc&sq=package:chromium&l=81&rcl=1421356211

**Comment by millisecond** [comment]
@mvano we’ve run into some tangles with this in implementation on several sites. 

Consider these two cases: 
- A single domain site needs more time to transition everything (CDN, videos, user-gen content, etc) to HTTPS but wants to use Chrome push.  An option would be to create a subdomain that uses HTTPS and is referred from the main site in an iframe.  https://push.blog.com for example.
- A multi-sub-domain site wants to register users only once but on several sub-domains.  www.blog.com and video.blog.com are separate and fail the equals test currently in Chromium.  A naive implementation would prompt the user twice and potentially send duplicate pushes if the site wasn’t very careful and separated the regs.  Would require a failure-prone cookie solution to work around that (or a bi-directional “do you have a reg?” series - complicated when there are many many sub-domains). If video.blog.com could iframe to a page on www.blog.com and have the registration happen there the user would be prompted once and never be sent duplicates.

In both cases I think the dialog wouldn’t be too confusing.  The domain doesn’t exactly match the page the user is on but, in my opinion, it’s something totally relevant to the context.

Proposal: allow iframes to register users for push if the top-level domains match.

**Comment by mvano** [comment]
Hi, as this is (intentionally) a browser-specific implementation detail, let's take the Chrome discussion to this Chrome bug: https://crbug.com/430496
