### ISSUE TITLE
Technique to Detect Endpoint Prior to register()

### ISSUE THREAD

**Issue by gauntface** [w3c/push-api#95]
Is there a way for a developer to detect what the current push service is for that device and use it show / hide push functionality based on what push services the back end supports?

For example, if my site supports push of GCM but not anything else, it would be ideal to hide the UI on other browsers / platforms which may support push but not GCM.

At the moment that only seems possible after the user has granted permission (unless I'm missing something).

**Comment by mvano** [comment]
The endpoint is not necessarily a constant, it can be registration specific. So it seems good for it to live on PushRegistration.

It sounds to me like you're looking to determine what Push Service is used. In future, this should not be necessary, because all services will use the same server to server protocol (IETF Web Push). For the intermediate period, I can't think of a nice solution yet, only hacky ones.

**Comment by jakearchibald** [comment]
Does the server-to-server protocol include registering with the push service? At the moment, as an "app owner" I need to register with GCM in order to get an API key to post messages, is that requirement going away?

**Comment by mvano** [comment]
Jake: that is also required. So that's another reason why we'll need a more short term solution or workaround. I'm hesitant to add something to the API though that only exists for handling cross-browser differences.

**Comment by gauntface** [comment]
Well this is different to cross-browser differences since its really the push services.

@mvano are you thinking that platforms may offer more than one push service which the user can then select?

Essentially, the developer has to offer the push functionality and then inform the user it's not supported - which looks pretty poor to the user since it would require a permission dialog, which now falls into limbo as to whether it's still granted or not.

I suppose that user agent sniffing is a possibility but that feels pretty hacky and error prone.

**Comment by mvano** [comment]
Yes theoretically a UA could have a setting for the preferred push service to use. So UA sniffing is not 100% correct. Certainly the same browser is likely to use different services on different platforms, so a platform check would be required when performing UA sniffing.

Agreed that there is no good solution for this yet:
- You could try to enumerate all possible services in the spec and expose the one in use, but that's not reasonable as the list is likely to grow.
- You could expose a service identifier as a DOMString for which the content is not specified. But that is still a bit sad because it enshrines forward incompatibility as part of the API: any new service would go unrecognized and not work until the site and service registration are updated.

What we really need is to either make advance registration with the service unnecessary, or coordinate some kind of universal registration across services, which needs to be performed only once.

**Comment by jakearchibald** [comment]
> Certainly the same browser is likely to use different services on different platforms

Yeah it's _sometimes_ the OS that dictates push service but it's _sometimes_ the browser.

> You could expose a service identifier as a DOMString for which the content is not specified. But that is still a bit sad because it enshrines forward incompatibility as part of the API: any new service would go unrecognized and not work until the site and service registration are updated.

How about something like `serviceWorkerRegistration.push.proprietaryService` which is a string containing the ID of the service (eg "GCM") or an empty string if the service is fully standard.

Services are considered fully standard if the communication is fully standard _and_ registration with the service unnecessary or follows some yet-to-be-defined standard automatable pattern.

**Comment by mvano** [comment]
I think nicer syntax would be `PushManager.proprietaryService` using the global interface object. No need to first register a SW that way.

I've tried to express my reluctance to making this concept part of the API. In the past, the Mozilla folks had some pretty strong opinions on this: @sicking @martinthomson @nikhilm

**Comment by jakearchibald** [comment]
`PushManager.proprietaryService` being non-empty should be seen as a black mark against the UA for not being as simple to use as the others :D

**Comment by martinthomson** [comment]
@jakearchibald :

> Does the server-to-server protocol include registering with the push service? At the moment, as an "app owner" I need to register with GCM in order to get an API key to post messages, is that requirement going away?

@mvano:

> Jake: that is also required. So that's another reason why we'll need a more short term solution or workaround. I'm hesitant to add something to the API though that only exists for handling cross-browser differences.

I think that the relevant people to bring in are @costinm and nero. 

In my opinion, ff the push service requires that application servers register, we have failed.  Managing multi-party relationships like that doesn't scale.  

I'm not against the application and push service opportunistically authenticating. For instance, Facebook might generate a lot of pushes, and so might have some way of signaling its pushes to GCM, which might enable separate accounting of those messages.  But I'd be strongly opposed to a scheme for authenticating applications if it were anything less than opportunistic.  @jakearchibald is right, if you require proprietary authentication, that makes you look bad.

**Comment by sicking** [comment]
It would probably be preferable to have a more explicit signal in the API for "This UA supports a standardized registration-free application-server-to-push-server protocol" rather than an empty `PushManager.proprietaryService` list. If for no other reason than that a UA might want to support proprietary services in addition to the standard one in order to support existing clients.

**Comment by jakearchibald** [comment]
> If for no other reason than that a UA might want to support proprietary services in addition to the standard one in order to support existing clients

Would a UA offer these up in new registrations?

To summarise, we're looking to do this: "Does the UA offer a push method I, as the site owner, can currently handle? If not, I'll send the name of the service to my server so I can investigate supporting it, but I won't offer the feature to the user."

**Comment by martinthomson** [comment]
> To summarise, we're looking to do this: "Does the UA offer a push method I, as the site owner, can currently handle? If not, I'll send the name of the service to my server so I can investigate supporting it, but I won't offer the feature to the user."

I'm specifically NOT looking to do that.  Or specifically looking to NOT do that.  Or something.  I think that we create the wrong incentives by doing so.  That said, I open to being convinced of it.

**Comment by sicking** [comment]
I would imagine that site authors would feel more comfortable with an explicit signal than an implicit one. I.e. as an author I'd worry that the list of proprietary services is empty due to a bug or due to a partial implementation, rather than an intentional action.

Second, yes, I would expect that UA implementations would want to keep supporting new registrations on proprietary protocols in order to support websites which have not yet implemented support for the standard protocol.

Otherwise the cost of rolling out support for the standard protocol becomes quite expensive and risky since it means that you're effectively having to drop existing features. Features that websites are definitely using.

**Comment by jakearchibald** [comment]
I'm worried less about protocol here, which sounds like it's on the way to being standardised, and more about any auth/registration that needs to happen with the service in advance.

When the UA provides a registration, what would make it provide an endpoint that needs service-to-service registration rather than one that doesn't? (assuming it supports both)

**Comment by sicking** [comment]
Perhaps we should require that by default the registration-free standard protocol is the one that's used. And if that's not supported by the UA, registration should fail. But also define that the registration call can accept a "protocol" parameter, where the page can choose to use a different different protocol if that's the only thing it supports (or that is has in common with the UA)

**Comment by sicking** [comment]
But yes, that's indeed a good question :)

**Comment by paul-em** [comment]
I have been thinking a lot about this issue lately, but I am not an expert in this field. But wouldn't it be possible to follow the IETF Web Push Protocol by adding a "relay server" and use this for the endpoint? 
This endpoint is provided by the user-agent and would have the Web Push protocol implemented and just forward the push messages to the actual push server. 
Once the push server implements the protocol itself, the endpoint could just change to use the actual push server and the relay server could shut down.

Correct me if I am wrong, but with this approach we could solve this issue of having to use multiple proprietary push services from the beginning on and therefore make it way easier to implement this feature right away without having to change it later as a developer.

**Comment by martinthomson** [comment]
@paul-em, this is one potential workaround, though this isn't ideal.  That adds latency.  It also raises the cost of shipping a browser (running servers for something like this isn't super-expensive, but it's not zero either).

**Comment by gauntface** [comment]
I think we all agree that push today is a bit of a pain because of the requirement for authenticating.

At the moment we return an endpoint after registration, could we offer up that endpoint (or list of endpoints) ahead of requesting permission (same as you can view a UA).

This at least gives the developer enough to make a decision (i.e. only support proprietary push API's, only support open standard push API's or a combo of both).

The end goal is that a developer won't have to worry about it, in the immediate / short term, this may prevent people from adopting the API.

**Comment by martinthomson** [comment]
@gauntface I think that that would be the wrong way to solve the problem.  It means that you can't rely on push being present in those applications.  That would, in my experience, make push unusable as a resplacement for the proprietary notification systems applications use today.  That negates much - if not all - of the advantage that a push service brings.

I'd rather see all the push services produce an endpoint that is properly open so that it can be reliably used by applications.

**Comment by gauntface** [comment]
@martinthomson so your proposal is that all push services should not be usable with this API until they decide to implement this new standard protocol?

**Comment by martinthomson** [comment]
My view is that if a browser implements this API, then it provides applications with an endpoint that conforms to the standard protocol, yes.  An endpoint for a proprietary protocol is essentially unusable.

Even if we add a protocol identification field we fail.  That is, unless everyone understands every possible value for the protocol identification field.  Though at that point you have a single standard protocol too, but it's really big and complex.

**Comment by gauntface** [comment]
Hence the API will be blocked on push services implementing changes - big negative since it blocks the API from being useful.

The alternative is to supply info on the push services via some API, including the notion of type (i.e. open standard or proprietary).

Regardless - identification of the service will be possible via the endpoint url, but that is post permission UI, which is a poor user experience.

If UA's will be able to use proprietary push services (like Chrome is today with GCM) - or it's an option for a UA, then an API to examine the endpoints pre-permission UI needs to be included.

**Comment by martinthomson** [comment]
> Hence the API will be blocked on push services implementing changes - big negative since it blocks the API from being useful.

Not so, though it requires that browsers provide the endpoint, as noted up thread.

What you propose doesn't improve the situation, it makes it worse by entrenching proprietary protocols.  It also exposes identifying information about users without any clear signal from the user that this is OK.

**Comment by gauntface** [comment]
Just to say, I don't want this to entrench proprietary protocols.

If anything ships with proprietary protocol usage however, the Push API will be horrible to use for a developer and a user. Dev - has to handle the period before the open standard is supported. User - has to handle not getting it after granting permission or expecting stuff to work, it doesn't and then makes the web as a whole seem inferior.

We have two options - help by supplying the endpoint url and info before requiring permission to use push, or cross our fingers and hope that developers and users figure stuff out and deal with any unusual issues.

I hadn't considered treating the endpoint URL as leaking information on the user - although I imagine this just masks the issues and encourages the use of UA sniffing to infer the endpoint, for the dedicated developers. (i.e. you're on Safari, probably Apples Push Service, you're on Chrome, probably GCM etc).

**Comment by martinthomson** [comment]
> If anything ships with proprietary protocol usage however, the Push API will be horrible to use for a developer and a user.

I can't agree more.  I think that where we disagree is how to best address the problem.

**Comment by gauntface** [comment]
I don't think this is going to move forward / be an issue anyone else is concerned about so let's continue moving forward with the spec as is and assume that UA sniffing is the best approach moving forward.

**Comment by costinm** [comment]
Sorry for late response - vacation.

There are few reasons why 'sender' registration is required in GCM - it may
be possible to allow sending without a registered sender ID in GCM, but it
would be with
a very low quota. I think avoiding the mistakes of SMTP is quite important,
operating a large push service is tricky and it is important to
authorize the senders and do some basic validations.

I would propose an alternative option: use the same protocol to register
senders as clients, which could be automated.

I think everyone agrees that the client will need a key pair,  and UA will
make a request to 'subscribe' to the push provider.
We need to finalize the details of this request - I would assume it will
include at least:
- public key of the app
- origin / package name / extension id
- some signature with the private key to prove ownership
- ID of the device
- some info about the UA ( at least impl & version )
- the public key of the authorized sender

The push service will return the subscription ID ( as URL ), and the URL
for its 'subscribe' endpoint.

The app server will get the subscription ID and 'subscribe' URL, and if it
is an unknown push service it will
make a similar 'subscribe' request as a client, proving that it controls
the public key ( sender public key ).

This model is similar with what is typically done for getting a cert for
HTTPS - except the steps will be automated
and obviously each push service will act as registry for public keys used
by all notes ( clients or servers) using that
service. All work on client will be done by the UA - the app only needs to
include the public key of the server.
The server will need some library similar with the UA - but I don't think
it will be very complicated, and push providers
may provide UI or integration to avoid/simplify this step for senders.

If we do this - it may be possible to operate without an app server -
assuming 2 apps instances can discover each other's
public key.

Costin
